version: "3"

services:
  app:
    image: motiullahsajit/preliminary:0.0.3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://untitled:oqdOLCDAfdbm4D09@cluster0.sxosl60.mongodb.net/preliminary?retryWrites=true&w=majority
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: preliminary
      MONGO_INITDB_ROOT_USERNAME: untitled
      MONGO_INITDB_ROOT_PASSWORD: oqdOLCDAfdbm4D09
    ports:
      - "27017:27017"
